---
excluded:
  - "**/.build"
  - "**/Package.swift"
force_cast: warning
force_try: warning
shorthand_operator: warning
type_body_length:
  warning: 250
  error: 10000
type_name:
  allowed_symbols:
    - _
only_rules:
#  - accessibility_label_for_image # 5 violations
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - array_init
  - async_without_await
  - attribute_name_spacing
#  - attributes # 136 violations
  - balanced_xctest_lifecycle
#  - blanket_disable_command # 2 violations
  - block_based_kvo
  - capture_variable
  - class_delegate_protocol
  - closing_brace
#  - closure_body_length # 12 violations
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comma_inheritance
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
#  - conditional_returns_on_newline # 5 violations
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
#  - contrasted_opening_brace # 2151 violations (fixable)
  - control_statement
#  - convenience_type # 1 violations
  - custom_rules
#  - cyclomatic_complexity # 3 violations
  - deployment_target
  - direct_return
  - discarded_notification_center_observer
#  - discouraged_assert # 1 violations
  - discouraged_direct_init
#  - discouraged_none_name # 1 violations
  - discouraged_object_literal
#  - discouraged_optional_boolean # 1 violations
  - discouraged_optional_collection
  - duplicate_conditions
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
#  - explicit_acl # 543 violations
#  - explicit_enum_raw_value # 4 violations
  - explicit_init
  - explicit_self
#  - explicit_top_level_acl # 45 violations
#  - explicit_type_interface # 827 violations
#  - extension_access_modifier # 1 violations
  - fallthrough
  - fatal_error_message
  - file_header
#  - file_length # 1 violations
#  - file_name # 28 violations
  - file_name_no_space
#  - file_types_order # 69 violations
  - final_test_case
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast # 1 violations
  - force_try # 13 violations
  - force_unwrapping # 25 violations
#  - function_body_length # 3 violations
#  - function_default_parameter_at_end # 21 violations
  - function_parameter_count
  - generic_type_name
  - ibinspectable_in_extension
#  - identical_operands # 4 violations
#  - identifier_name # 120 violations
  - implicit_getter
  - implicit_optional_initialization
  - implicit_return
  - implicitly_unwrapped_optional
  - inclusive_language
#  - indentation_width # 6 violations
  - invalid_swiftlint_command
  - is_disjoint
  - joined_default_parameter
#  - large_tuple # 1 violations
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
#  - legacy_multiple # 1 violations
  - legacy_nsgeometry_functions
  - legacy_objc_type
  - legacy_random
#  - let_var_whitespace # 14 violations
#  - line_length # 268 violations
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - mark
#  - missing_docs # 368 violations
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
#  - multiple_closures_with_trailing_closure # 1 violations
#  - nesting # 3 violations
  - nimble_operator
#  - no_empty_block # 4 violations
#  - no_extension_access_modifier # 134 violations
  - no_fallthrough_only
#  - no_grouping_extension # 69 violations
#  - no_magic_numbers # 477 violations
  - no_space_in_method_call
  - non_optional_string_data_conversion
  - non_overridable_class_declaration
  - notification_center_detachment
  - ns_number_init_as_function_reference
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
#  - one_declaration_per_file # 61 violations
  - opening_brace
  - operator_usage_whitespace
#  - operator_whitespace # 1 violations
  - optional_data_string_conversion
  - optional_enum_case_matching
  - orphaned_doc_comment
  - overridden_super_call
  - override_in_extension
#  - pattern_matching_keywords # 16 violations
  - period_spacing
  - prefer_condition_list # 1 violations (fixable)
  - prefer_key_path
  - prefer_nimble
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_type_checking
  - prefer_zero_over_explicit_init
#  - prefixed_toplevel_constant # 10 violations
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_subject
  - private_swiftui_state
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_self_in_closure
  - redundant_sendable
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
#  - required_deinit # 15 violations
  - required_enum_case
  - return_arrow_whitespace
  - return_value_from_void_function
  - self_binding
  - self_in_property_initialization
  - shorthand_argument
  - shorthand_operator
  - shorthand_optional_binding
  - single_test_class
#  - sorted_enum_cases # 31 violations
  - sorted_first_last
  - sorted_imports
#  - statement_position # 28 violations (fixable)
  - static_operator
  - static_over_final_class
#  - strict_fileprivate # 4 violations
  - strong_iboutlet
#  - superfluous_disable_command # 1 violations
  - superfluous_else
  - switch_case_alignment
#  - switch_case_on_newline # 13 violations
  - syntactic_sugar
  - test_case_accessibility
#  - todo # 56 violations
  - toggle_bool
  - trailing_closure
  - trailing_comma # 5 violations (fixable)
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace # 2 violations (fixable)
#  - type_body_length # 1 violations
#  - type_contents_order # 107 violations
  - type_name # 3 violations
  - typesafe_array_init
  - unavailable_condition
  - unavailable_function
#  - unhandled_throwing_task # 1 violations
  - unneeded_break_in_switch
  - unneeded_override
  - unneeded_parentheses_in_closure_argument
  - unneeded_synthesized_initializer
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
#  - unused_parameter # 43 violations (fixable)
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
#  - vertical_whitespace_between_cases # 84 violations (fixable)
  - vertical_whitespace_closing_braces # 1 violations (fixable)
  - vertical_whitespace_opening_braces
  - void_function_in_ternary
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition
